namespace Cards.Enum
{
    public enum CardActionType
    {
        AddBonusManaEffected,
        Decrease2MaxMana,
        DecreaseIncrease2Mana,
        DestroyFreeze,
        Freeze3CellEffected,
        Freeze6Figure,
        FreezeAllMana,
        FreezeCell,
        FreezeCellGroup,
        FullHouse,
        IceEncirclement,
        Increase2MaxMana,
        ManaPerIce,
        PlaceAroundFreeze,
        PlaceFigure,
        PlaceFigureEffected,
        PlaceFigureWithAddCard,
        PlaceMore,
        PlaceRandom5,
        Random2Mana,
        Restore1Mana,
        Restore3Mana,
        RestoreAllMana,
        Shortage,
        SurroundedByIce
    }
}